### ISSUE TITLE
Unknown runtime error with PID 15964

### ISSUE THREAD

**Issue by pereved** [zhanghai/AndroidFastScroll#14]
Hello. An unobvious error occurs due to pop-up styles. I can’t understand what the problem is. Here is a sample code:

## Fragment:
    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)

        setupRenderer()
    }

    private fun setupRenderer() {
        renderer = IndexedAdapter(DiffCallback())

        renderer.apply {
            registerRenderer(NotesRenderer())
        }

        fastScrollRecyclerViewNotes.adapter = renderer

        FastScrollerBuilder(fastScrollRecyclerViewNotes)
            .useMd2Style()
            .build()

        fastScrollRecyclerViewNotes.enableVerticalOverScroll()
    }

## Xml:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:parentTag="androidx.coordinatorlayout.widget.CoordinatorLayout">

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/fastScrollRecyclerViewNotes"
        style="@style/GirdFastScrollList"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:listitem="@layout/cell_note" />

</RelativeLayout>

## Logcat:

    2020-04-08 16:02:33.275 15964-15964/com.pereved.schedule E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pereved.schedule, PID: 15964
    java.lang.BootstrapMethodError: Exception from call site #4 bootstrap method
        at me.zhanghai.android.fastscroll.PopupStyles.<clinit>(PopupStyles.java:34)
        at me.zhanghai.android.fastscroll.FastScrollerBuilder.useDefaultStyle(FastScrollerBuilder.java:113)
        at me.zhanghai.android.fastscroll.FastScrollerBuilder.<init>(FastScrollerBuilder.java:59)
        at com.pereved.schedule.notes.list.view.NotesListFragment.setupRenderer(NotesListFragment.kt:99)
        at com.pereved.schedule.notes.list.view.NotesListFragment.onActivityCreated(NotesListFragment.kt:52)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2717)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at me.zhanghai.android.fastscroll.PopupStyles.<clinit>(PopupStyles.java:34) 
        at me.zhanghai.android.fastscroll.FastScrollerBuilder.useDefaultStyle(FastScrollerBuilder.java:113) 
        at me.zhanghai.android.fastscroll.FastScrollerBuilder.<init>(FastScrollerBuilder.java:59) 
        at com.pereved.schedule.notes.list.view.NotesListFragment.setupRenderer(NotesListFragment.kt:99) 
        at com.pereved.schedule.notes.list.view.NotesListFragment.onActivityCreated(NotesListFragment.kt:52) 
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2717) 
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188) 
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849) 
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

Everything works without these lines:
    
    FastScrollerBuilder(fastScrollRecyclerViewNotes)
        .useMd2Style()
        .build()

In my adapter I override PopupTextProvider but my application fails and I can’t understand what the problem is.. Your library example didn't help me.

## Specifications

- Version: 1.1.2
- Platform: Android 9

**Comment by zhanghai** [comment]
[PopupStyles.java#34](https://github.com/zhanghai/AndroidFastScroll/blob/32ebe0666d298a552f9a6859dc652f31611246fd/library/src/main/java/me/zhanghai/android/fastscroll/PopupStyles.java#L34) is just creating a lambda instance.If the sample app works on your device, it should be something with your project configuration. e.g. Did you set both your Java and Kotlin compile option to produce Java 8 bytecode?

**Comment by pereved** [comment]
> [PopupStyles.java#34](https://github.com/zhanghai/AndroidFastScroll/blob/32ebe0666d298a552f9a6859dc652f31611246fd/library/src/main/java/me/zhanghai/android/fastscroll/PopupStyles.java#L34) is just creating a lambda instance.If the sample app works on your device, it should be something with your project configuration. e.g. Did you set both your Java and Kotlin compile option to produce Java 8 bytecode?

Thank you. Added this compile options lines helped me:

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }


Could you add detailed instructions on customizing and styling your library to the ReadMe.txt file? Your examples from the samples package are unfortunately difficult to understand.
