### ISSUE TITLE
App crash with PID 12925

### ISSUE THREAD

**Issue by jesusignazio** [zhanghai/AndroidFastScroll#22]
`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jiggdev.visorfondos, PID: 12925
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.art/javalib/core-oj.jar)
        at me.zhanghai.android.fastscroll.PopupStyles.<clinit>(PopupStyles.java:34)
        at me.zhanghai.android.fastscroll.FastScrollerBuilder.useDefaultStyle(FastScrollerBuilder.java:122)
        at me.zhanghai.android.fastscroll.FastScrollerBuilder.<init>(FastScrollerBuilder.java:62)
        at com.jiggdev.visorfondos.fragments.Fragment_Activos.setRecyclerView(Fragment_Activos.java:61)
        at com.jiggdev.visorfondos.fragments.Fragment_Activos.onViewCreated(Fragment_Activos.java:54)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:322)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7478)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
I/Process: Sending signal. PID: 12925 SIG: 9`

FastScroller fastScroller = new FastScrollerBuilder(rv).build();

## build.gradle
implementation 'androidx.recyclerview:recyclerview:1.1.0'
implementation 'androidx.appcompat:appcompat:1.1.0'
implementation 'me.zhanghai.android.fastscroll:library:1.1.4'

## Specifications

compileSdkVersion 29
buildToolsVersion "29.0.3"

**Comment by zhanghai** [comment]
Please use Java 8 bytecode in your project.

```
android {
  ...
  // Configure only for each module that uses Java 8
  // language features (either in its source code or
  // through dependencies).
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
  // For Kotlin projects
  kotlinOptions {
    jvmTarget = "1.8"
  }
}
```

**Comment by jesusignazio** [comment]
Thanks. It solved it. 
Please provide that info in the README.md

**Comment by zhanghai** [comment]
Added.
