### ISSUE TITLE
Fatal Exception: java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by cico1980** [zhanghai/AndroidFastScroll#45]
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at me.zhanghai.android.fastscroll.FastScroller.scrollToThumbOffset(FastScroller.java:380)
       at me.zhanghai.android.fastscroll.FastScroller.onTouchEvent(FastScroller.java:325)
       at me.zhanghai.android.fastscroll.FastScroller.$r8$lambda$rTQcs5gqTpHxYd9ar1i9VccEjvo(FastScroller.java)
       at me.zhanghai.android.fastscroll.FastScroller$$InternalSyntheticLambda$0$1818e04b76f0a8b5d0fca4db696fe741088ef0340e11119ee7db05a1ef50bbbd$3.test(FastScroller.java:4)
       at me.zhanghai.android.fastscroll.RecyclerViewHelper$3.onTouchEvent(RecyclerViewHelper.java:78)
       at androidx.recyclerview.widget.RecyclerView.dispatchToOnItemTouchListeners(RecyclerView.java:3259)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3421)
       at android.view.View.dispatchTouchEvent(View.java:15076)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3917)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3581)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1015)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4265)

## Specifications

- Version: 1.1.7
- Platform: Galaxy S10 Android version 12

**Comment by zhanghai** [comment]
It means for your view `mView.getHeight() - padding.top - padding.bottom - mThumbHeight` is `0`. Maybe the view is too small or the padding/thumb is too large?
